all:
	gcc -o thingplus main.c pir.c htx23c.c -lthingplus -lpthread -lrt -lmosquitto -ljson-c -lcurl -g   -lmodbus
	#mipsel-openwrt-linux-gcc -o thingplus_cn main.c pir.c htx23c.c -lthingplus -lpthread -lrt -lmosquitto -ljson-c -lcurl -g -lmodbus
